services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Andser\BitfinexBundle\Service\Api: ~

    andser.bitfinex.api:
        alias: Andser\BitfinexBundle\Service\Api
        public: true
